name = "GradDescent"
uuid = "76767984-a792-11e8-2bb2-77d388f79a09"
authors = ["Jacob Carey"]
version = "0.3.2"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.0"
Distributions = "0.21.8"

[targets]
test = ["Test","ForwardDiff","Random"]
